version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0.33
    container_name: shopkart-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopkart_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Shopkart Authorization OAuth2 Server
  shopkart-auth:
    build: .
    container_name: shopkart-auth-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopkart_auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql-data:
